# Data Science Tools and Ecosystem

In this notebook, Data Science Tools and Ecosystem are summarized.

## Some of the popular languages that Data Scientists use are:
1. Python
2. R
3. SQL

## Some of the commonly used libraries used by Data Scientists include:
1. Pandas
2. NumPy
3. Matplotlib

## Data Science Tools
| Data Science Tools |
|-------------------|
| Jupyter Notebook  |
| RStudio           |
| Apache Zeppelin   |

### Below are a few examples of evaluating arithmetic expressions in Python:

In [ ]:
# This is a simple arithmetic expression to multiply and then add integers
(3 * 4) + 5

### Convert 200 minutes to hours:

In [ ]:
# This will convert 200 minutes to hours by dividing by 60
200 / 60

**Objectives:**
- List popular languages for Data Science
- List commonly used libraries
- Demonstrate basic arithmetic operations in Python
- Show how to convert minutes to hours

## Author
Jesus Francisco